server:
  port: 8090 


spring:
    data:
       mongodb:
          database: test
          host: localhost
          port: 27017
    mvc:
      view:
        prefix: /templates/
        suffix: .jsp
        
